import type { Product } from "./store";

export const dogsAndCatsCategory = {
  id: "dogs-cats",
  name: "Dogs & Cats",
  slug: "dogs-cats",
  image: "https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=800",
  description: "Premium food, toys, grooming & accessories for dogs and cats",
  featured: true,
  subcategories: [
    { name: "Dog Food", slug: "dog-food" },
    { name: "Cat Food", slug: "cat-food" },
    { name: "Toys", slug: "toys" },
    { name: "Grooming", slug: "grooming" },
    { name: "Beds", slug: "beds" },
    { name: "Accessories", slug: "pet-accessories" },
  ],
};

export const dogsAndCatsProducts: Product[] = [
  // Dog Food
  {
    id: "dc-dogfood-1",
    name: "Royal Canin Adult Dog Food",
    slug: "royal-canin-adult-dog-food",
    category: "dogs-cats",
    subcategory: "dog-food",
    price: 1899,
    originalPrice: 2199,
    images: ["https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?w=800"],
    description: "Complete and balanced nutrition for adult dogs. Supports healthy digestion and immune system.",
    specifications: { Weight: "3kg", "Life Stage": "Adult", Breed: "All Breeds" },
    variants: [{ name: "Size", options: ["3kg", "7.5kg", "15kg"] }],
    inStock: true,
    isFeatured: true,
    rating: 4.8,
    reviews: 312,
    tags: ["dog", "food", "royal-canin", "adult"],
  },
  {
    id: "dc-dogfood-2",
    name: "Pedigree Adult Dry Dog Food",
    slug: "pedigree-adult-dry-dog-food",
    category: "dogs-cats",
    subcategory: "dog-food",
    price: 799,
    originalPrice: 999,
    images: ["https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=800"],
    description: "Wholesome nutrition with chicken and vegetables. Promotes strong bones and healthy coat.",
    specifications: { Weight: "3kg", "Life Stage": "Adult", Flavor: "Chicken & Vegetables" },
    variants: [{ name: "Size", options: ["1.2kg", "3kg", "10kg"] }],
    inStock: true,
    isFeatured: true,
    rating: 4.5,
    reviews: 567,
    tags: ["dog", "food", "pedigree", "dry"],
  },
  {
    id: "dc-dogfood-3",
    name: "Drools Puppy Dog Food",
    slug: "drools-puppy-dog-food",
    category: "dogs-cats",
    subcategory: "dog-food",
    price: 649,
    images: ["https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?w=800"],
    description: "High protein puppy food with DHA for brain development. Perfect for puppies up to 12 months.",
    specifications: { Weight: "3kg", "Life Stage": "Puppy", Flavor: "Chicken & Egg" },
    variants: [{ name: "Size", options: ["3kg", "6kg", "12kg"] }],
    inStock: true,
    isNew: true,
    rating: 4.6,
    reviews: 234,
    tags: ["dog", "food", "drools", "puppy"],
  },
  {
    id: "dc-dogfood-4",
    name: "Farmina N&D Grain Free Dog Food",
    slug: "farmina-nd-grain-free-dog-food",
    category: "dogs-cats",
    subcategory: "dog-food",
    price: 3499,
    originalPrice: 3999,
    images: ["https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800"],
    description: "Premium grain-free formula with fresh chicken and pomegranate. Ideal for sensitive dogs.",
    specifications: { Weight: "2.5kg", "Life Stage": "Adult", Type: "Grain Free" },
    variants: [{ name: "Size", options: ["2.5kg", "7kg"] }],
    inStock: true,
    isFeatured: true,
    rating: 4.9,
    reviews: 145,
    tags: ["dog", "food", "farmina", "grain-free", "premium"],
  },
  // Cat Food
  {
    id: "dc-catfood-1",
    name: "Royal Canin Indoor Cat Food",
    slug: "royal-canin-indoor-cat-food",
    category: "dogs-cats",
    subcategory: "cat-food",
    price: 1699,
    originalPrice: 1999,
    images: ["https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800"],
    description: "Specially formulated for indoor cats. Reduces hairballs and maintains healthy weight.",
    specifications: { Weight: "2kg", "Life Stage": "Adult", Type: "Indoor" },
    variants: [{ name: "Size", options: ["2kg", "4kg", "10kg"] }],
    inStock: true,
    isFeatured: true,
    rating: 4.8,
    reviews: 289,
    tags: ["cat", "food", "royal-canin", "indoor"],
  },
  {
    id: "dc-catfood-2",
    name: "Whiskas Adult Cat Food",
    slug: "whiskas-adult-cat-food",
    category: "dogs-cats",
    subcategory: "cat-food",
    price: 599,
    originalPrice: 749,
    images: ["https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800"],
    description: "Complete nutrition with ocean fish flavor. Supports healthy heart and vision.",
    specifications: { Weight: "1.2kg", "Life Stage": "Adult", Flavor: "Ocean Fish" },
    variants: [{ name: "Size", options: ["480g", "1.2kg", "3kg"] }],
    inStock: true,
    rating: 4.5,
    reviews: 423,
    tags: ["cat", "food", "whiskas", "adult"],
  },
  {
    id: "dc-catfood-3",
    name: "Purina Pro Plan Kitten Food",
    slug: "purina-pro-plan-kitten-food",
    category: "dogs-cats",
    subcategory: "cat-food",
    price: 2199,
    images: ["https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=800"],
    description: "High protein kitten food with DHA for brain and vision development. Real chicken as first ingredient.",
    specifications: { Weight: "1.5kg", "Life Stage": "Kitten", Flavor: "Chicken" },
    variants: [{ name: "Size", options: ["1.5kg", "3kg"] }],
    inStock: true,
    isNew: true,
    isFeatured: true,
    rating: 4.9,
    reviews: 178,
    tags: ["cat", "food", "purina", "kitten", "premium"],
  },
  {
    id: "dc-catfood-4",
    name: "Sheba Premium Wet Cat Food",
    slug: "sheba-premium-wet-cat-food",
    category: "dogs-cats",
    subcategory: "cat-food",
    price: 349,
    originalPrice: 420,
    images: ["https://images.unsplash.com/photo-1533743983669-94fa5c4338ec?w=800"],
    description: "Delicious wet food pouches with real tuna and salmon. No artificial preservatives.",
    specifications: { Weight: "6 x 70g", Type: "Wet Food", Flavor: "Tuna & Salmon" },
    variants: [{ name: "Pack", options: ["6 pouches", "12 pouches", "24 pouches"] }],
    inStock: true,
    rating: 4.7,
    reviews: 356,
    tags: ["cat", "food", "sheba", "wet", "tuna"],
  },
  // Toys
  {
    id: "dc-toys-1",
    name: "Interactive Dog Puzzle Toy",
    slug: "interactive-dog-puzzle-toy",
    category: "dogs-cats",
    subcategory: "toys",
    price: 699,
    originalPrice: 899,
    images: ["https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=800"],
    description: "Mental stimulation puzzle toy for dogs. Hides treats to keep dogs engaged and reduce boredom.",
    specifications: { Material: "BPA-Free Plastic", "Difficulty": "Level 2", "Suitable For": "All Breeds" },
    inStock: true,
    isFeatured: true,
    rating: 4.7,
    reviews: 234,
    tags: ["dog", "toy", "puzzle", "interactive", "treat"],
  },
  {
    id: "dc-toys-2",
    name: "Cat Feather Wand Toy",
    slug: "cat-feather-wand-toy",
    category: "dogs-cats",
    subcategory: "toys",
    price: 299,
    images: ["https://images.unsplash.com/photo-1535930891776-0c2dfb7fda1a?w=800"],
    description: "Extendable feather wand for interactive play. Stimulates natural hunting instincts in cats.",
    specifications: { Length: "60cm extended", Material: "Feather & Plastic", "For": "Cats" },
    inStock: true,
    rating: 4.6,
    reviews: 312,
    tags: ["cat", "toy", "feather", "wand", "interactive"],
  },
  {
    id: "dc-toys-3",
    name: "Rope Chew Toy for Dogs",
    slug: "rope-chew-toy-dogs",
    category: "dogs-cats",
    subcategory: "toys",
    price: 399,
    originalPrice: 499,
    images: ["https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=800"],
    description: "Durable cotton rope toy for chewing and tug-of-war. Helps clean teeth and massage gums.",
    specifications: { Material: "100% Cotton", Size: "Medium", "Suitable For": "Medium to Large Dogs" },
    variants: [{ name: "Size", options: ["Small", "Medium", "Large"] }],
    inStock: true,
    rating: 4.5,
    reviews: 189,
    tags: ["dog", "toy", "rope", "chew", "tug"],
  },
  {
    id: "dc-toys-4",
    name: "Cat Tunnel & Ball Set",
    slug: "cat-tunnel-ball-set",
    category: "dogs-cats",
    subcategory: "toys",
    price: 549,
    images: ["https://images.unsplash.com/photo-1601758174493-45d0a4d3e407?w=800"],
    description: "Collapsible crinkle tunnel with peek-a-boo holes and a bonus ball toy. Hours of fun for cats.",
    specifications: { Length: "90cm", Material: "Polyester", "For": "Cats" },
    inStock: true,
    isNew: true,
    rating: 4.8,
    reviews: 156,
    tags: ["cat", "toy", "tunnel", "ball", "crinkle"],
  },
  // Grooming
  {
    id: "dc-grooming-1",
    name: "Pet Grooming Brush - Deshedding",
    slug: "pet-grooming-deshedding-brush",
    category: "dogs-cats",
    subcategory: "grooming",
    price: 499,
    originalPrice: 649,
    images: ["https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800"],
    description: "Professional deshedding brush reduces shedding by up to 90%. Suitable for dogs and cats.",
    specifications: { Material: "Stainless Steel", "For": "Dogs & Cats", "Coat Type": "All Coats" },
    inStock: true,
    isFeatured: true,
    rating: 4.7,
    reviews: 445,
    tags: ["grooming", "brush", "deshedding", "dog", "cat"],
  },
  {
    id: "dc-grooming-2",
    name: "Pet Shampoo - Oatmeal & Aloe",
    slug: "pet-shampoo-oatmeal-aloe",
    category: "dogs-cats",
    subcategory: "grooming",
    price: 349,
    images: ["https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=800"],
    description: "Gentle oatmeal and aloe vera shampoo for sensitive skin. Soap-free and tear-free formula.",
    specifications: { Volume: "500ml", "Skin Type": "Sensitive", "For": "Dogs & Cats" },
    inStock: true,
    rating: 4.6,
    reviews: 267,
    tags: ["grooming", "shampoo", "oatmeal", "sensitive"],
  },
  // Beds
  {
    id: "dc-beds-1",
    name: "Orthopedic Dog Bed",
    slug: "orthopedic-dog-bed",
    category: "dogs-cats",
    subcategory: "beds",
    price: 1499,
    originalPrice: 1999,
    images: ["https://images.unsplash.com/photo-1583511655826-05700d52f4d9?w=800"],
    description: "Memory foam orthopedic bed for joint support. Waterproof cover with removable washable liner.",
    specifications: { Size: "Medium (70x50cm)", Material: "Memory Foam", "For": "Dogs" },
    variants: [{ name: "Size", options: ["Small", "Medium", "Large", "XL"] }],
    inStock: true,
    isFeatured: true,
    rating: 4.8,
    reviews: 198,
    tags: ["dog", "bed", "orthopedic", "memory-foam"],
  },
  {
    id: "dc-beds-2",
    name: "Cat Cave Bed",
    slug: "cat-cave-bed",
    category: "dogs-cats",
    subcategory: "beds",
    price: 899,
    images: ["https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800"],
    description: "Cozy enclosed cave bed for cats who love to hide and sleep. Soft plush interior with non-slip base.",
    specifications: { Size: "40cm diameter", Material: "Plush", "For": "Cats" },
    variants: [{ name: "Color", options: ["Grey", "Brown", "Pink"] }],
    inStock: true,
    rating: 4.7,
    reviews: 234,
    tags: ["cat", "bed", "cave", "cozy", "plush"],
  },
  // Accessories
  {
    id: "dc-acc-1",
    name: "Adjustable Dog Harness",
    slug: "adjustable-dog-harness",
    category: "dogs-cats",
    subcategory: "pet-accessories",
    price: 599,
    originalPrice: 799,
    images: ["https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=800"],
    description: "No-pull adjustable harness with reflective strips for night safety. Easy step-in design.",
    specifications: { Material: "Nylon", "Closure": "Buckle", "For": "Dogs" },
    variants: [{ name: "Size", options: ["XS", "S", "M", "L", "XL"] }],
    inStock: true,
    rating: 4.6,
    reviews: 312,
    tags: ["dog", "harness", "no-pull", "reflective"],
  },
  {
    id: "dc-acc-2",
    name: "Cat Collar with Bell",
    slug: "cat-collar-with-bell",
    category: "dogs-cats",
    subcategory: "pet-accessories",
    price: 199,
    images: ["https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800"],
    description: "Breakaway safety collar with bell and ID tag ring. Adjustable for all cat sizes.",
    specifications: { Material: "Nylon", "Safety": "Breakaway Buckle", "For": "Cats" },
    variants: [{ name: "Color", options: ["Red", "Blue", "Pink", "Black"] }],
    inStock: true,
    rating: 4.5,
    reviews: 189,
    tags: ["cat", "collar", "bell", "safety"],
  },
];
